[tools]
bun = "latest"
go = "latest"
java = "openjdk-17.0.2"
node = "24"
"npm:@angular/cli" = "latest"
"npm:@nestjs/cli" = "latest"
"npm:@agent-browser" = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
uv = "latest"
