[tools]
aube = "latest"
bun = "latest"
"cargo:create-tauri-app" = "latest"
"cargo:tauri-cli" = "latest"
"cargo:trunk" = "latest"
go = "latest"
herdr = "latest"
java = "openjdk-17.0.2"
node = "24"
"npm:@angular/cli" = "latest"
"npm:@nestjs/cli" = "latest"
"npm:agent-browser" = "latest"
pnpm = "11.20.0"
python = "latest"
rust = "latest"
uv = "latest"
