[tools]
bun = "latest"
"cargo:create-tauri-app" = "latest"
"cargo:tauri-cli" = "^2"
"cargo:trunk" = "latest"
go = "latest"
java = "openjdk-17.0.2"
node = "24"
"npm:@angular/cli" = "latest"
"npm:@nestjs/cli" = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
uv = "latest"
